server:
  port: 8080

spring:
  application:
    name: course
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  jmx:
    enabled: false
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
